# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Snappy Jekyll
description: > # this means to ignore newlines until "baseurl:"
  A setup for making snappy static sites with Jekyll, Webpack, Tailwind, and Turbolinks
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

exclude: [
  'node_modules'
]

sass:
  style: compressed

# Build settings
markdown: kramdown
